name: multimesh
description: "A cross-platform Meshtastic client based on Flutter"

publish_to: 'none'

version: 0.2.1+17

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  chat_bubbles: ^1.6.0
  convert: ^3.1.1
  crypto: ^3.0.3
  csv: ^5.1.1
  easy_debounce: ^2.0.3
  file_saver: ^0.2.12
  firebase_analytics: ^10.10.1
  firebase_core: ^2.29.0
  firebase_crashlytics: ^3.5.1
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.7
  flutter_foreground_task: ^6.1.3
  flutter_local_notifications: ^17.0.0
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  http: ^1.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  mobile_scanner: ^4.0.1
  mockito: ^5.4.4
  package_info_plus: ^8.0.0
  path: ^1.9.0
  permission_handler: ^11.1.0
  platform: ^3.1.4
  protobuf: ^3.1.0
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.3.3
  scrollview_observer: ^1.19.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.8
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/meshx.png"
  min_sdk_android: 21
  remove_alpha_ios: true
